version: '2.1'

services:
 mysql:
  image: mysql:latest
  environment:
  - MYSQL_ROOT_PASSWORD=root
  - MYSQL_DATABASE=db_example
  - MYSQL_USER=springuser
  - MYSQL_PASSWORD=pass
 vulnerable-api:
  image: vulnerable-api
  depends_on:
   - mysql
  ports:
   - 8080:8080
  environment:
   - DATABASE_PORT=3306
   - DATABASE_NAME=db_example
   - DATABASE_USER=springuser
   - DATABASE_PASSWORD=pass
   - DATABASE_HOST=mysql
