spring:
  datasource:
    url: jdbc:mysql://172.18.0.2:3306/db_example
    username: springuser
    password: pass
    platform: mysql
#    data: data-mysql.sql
#    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://172.18.0.2:3306/db_example
    username: springuser
    password: pass
#    initialize: true