spring:
  datasource:
    url: jdbc:mysql://172.18.0.2:3306/db_example
    username: springuser
    password: pass
    platform: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: validate
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://172.18.0.2:3306/db_example
    username: springuser
    password: pass
  jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      hibernate:
        use-new-id-generator-mappings: false
        ddl-auto: validate